#WINDOW PROP
SCREEN_WIDTH = 1680 #drawable part of screen
WINDOW_WIDTH = 1024
WINDOW_HEIGHT = 512
ARRAY_SIZE = 8 #default, 2^n
MENU_WIDTH = SCREEN_WIDTH - WINDOW_WIDTH

#FONT
FONT_NAME = 'comicsans'

RATIO = int(WINDOW_WIDTH / ARRAY_SIZE)
